version: "3.8"

services:
  app:
    build: .
    container_name: document-manager
    ports:
      - "5214:5214"
    env_file:
      - .env
    volumes:
      - /mnt/data/media/document-manager/uploads:/opt/apps/document-manager/uploads
    restart: unless-stopped
