version: "3.8"

services:
  app:
    build: .
    container_name: document-manager
    ports:
      - "5214:5214"
    env_file:
      - .env
    volumes:
      - doc-uploads:/opt/apps/document-manager/uploads
    restart: unless-stopped

volumes:
  doc-uploads:
